START_WINDOW_TITLE = 'Guess the game starter'

START_WINDOW_HEIGHT = 500

START_WINDOW_WIDTH = 900

ATTEMPTS = 5

MAX_NUMBER_TO_CONCEIVE = 100

CONNECTION_TO_SERVER_TIMEOUT = 5

GAME_WINDOW_TITLE = 'Guess the number game'

GAME_WINDOW_HEIGHT = 500

GAME_WINDOW_WIDTH = 900

TABS = '\t' * 6

PARAGRAPHS = '\n' * 2
